### ISSUE TITLE
CsvProcessor fails on Excel files when sheet_name is not given

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/etk#264]
```
Traceback (most recent call last):
  File "/Users/pszekely/github/etk-pedro/examples/events_ucdp/ucdp_module.py", line 48, in <module>
    docs = cp.tabular_extractor(filename="ucdp_sample.xls", data_set='ucdp')
  File "/Users/pszekely/github/etk-pedro/examples/events_ucdp/../../etk/csv_processor.py", line 107, in tabular_extractor
    sheet_name = data.key()[0]
AttributeError: 'collections.OrderedDict' object has no attribute 'key'
```

**Comment by saggu** [comment]
Closing
